/*
    SUBQUERY (서브쿼리)
     - 하나의 SQL문 안에 포함된 또 다른 SQL문
*/

-- 1. 
-- 노옹철 사원의 부서코드 조회
SELECT EMP_NAME, DEPT_CODE FROM EMPLOYEE
WHERE EMP_NAME = '노옹철';

-- 부서코드가 D9인 사원들 조회
SELECT EMP_NAME, DEPT_CODE FROM EMPLOYEE
WHERE DEPT_CODE = 'D9';

-- 2. SUBQUERY
-- 노옹철 사원과 같은 부서원들을 조회
SELECT * FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE
WHERE EMP_NAME = '노옹철');

-- 전 직원의 평균 급여보다 더 많은 급여를 받는 사원들 조회

SELECT EMP_NAME, SALARY FROM EMPLOYEE; -- A
SELECT ROUND(AVG(SALARY)) FROM EMPLOYEE; -- B

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

/*
    SUBQUERY TYPES
     - 서브쿼리를 수행한 결과값이 몇 행 몇 열이냐에 따라서 분류
     - 서브쿼리의 종류에 따라 서브쿼리 앞에 붙는 연산자가 달라짐
    
    1. 단일행 서브쿼리
     - 서브쿼리의 조회 결과값의 개수가 오로지 1개일 때 (한 행 한 열)
     - 일반 비교연산자 사용 가능 : =, !=, >, <, >=, <=
*/

-- 노옹철 사원의 급여보다 더 많이 받는 사원들 조회
SELECT * FROM EMPLOYEE
WHERE EMP_NAME = '노옹철'; -- 노옹철

SELECT SALARY FROM EMPLOYEE
WHERE EMP_NAME = '노옹철'; -- 노옹철 급여

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY > 3700000; -- 노옹철 급여 보다 많은 사원

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY > (SELECT SALARY FROM EMPLOYEE WHERE EMP_NAME = '노옹철');

-- 부서별 급여의 합SUM()이 가장 큰MAX() 부서의 부서코드, 급여 합 조회
SELECT DEPT_CODE, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D9'; -- SALARIES IN D9

SELECT MAX(SUM(SALARY))
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT DEPT_CODE, SUM(SALARY) FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING SUM(SALARY) = (SELECT MAX(SUM(SALARY))
FROM EMPLOYEE
GROUP BY DEPT_CODE);

-- 전지연 사원이 속해 있는 부서원들 조회 (단, 전지연 제외)
SELECT EMP_NAME, DEPT_CODE FROM EMPLOYEE
WHERE DEPT_CODE = 'D1'  -- 전지연과 같은 부서원
MINUS
SELECT EMP_NAME, DEPT_CODE FROM EMPLOYEE
WHERE EMP_NAME = '전지연'; -- 전지연이 속한 부서는 D1 (순서 중요!)

SELECT * FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';

/*
    2. 다중행 서브쿼리
     - 서브쿼리 조회 결과 값의 개수가 여러 행 일 때 (여러행 한 열)

    IN SUBQUERY : 여러 개의 결과값 중에서 한 개라도 일치하는 값이 있다면
*/

-- 각 부서별 최고 급여를 받는 사원들 조회
SELECT DEPT_CODE, EMP_NAME, SALARY
FROM EMPLOYEE
WHERE (DEPT_CODE, SALARY) IN (
    SELECT DEPT_CODE, MAX(SALARY)
    FROM EMPLOYEE
    GROUP BY DEPT_CODE
);

-- 사원에 대해 사번, 이름, 부서 코드, 구분(사수/사원) 조회
-- MANAGER_ID가 있다면 사수가 있다는 소리 즉, 사원
-- 없다면 사수가 없으니 본인이 사수

SELECT * FROM EMPLOYEE;
SELECT EMP_NO, EMP_NAME, DEPT_CODE, MANAGER_ID FROM EMPLOYEE
WHERE MANAGER_ID IS NOT NULL;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, NVL2(MANAGER_ID, '사원', '사수') AS 구분
FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, DEPT_CODE,
CASE 
WHEN MANAGER_ID IS NULL THEN '사수'
WHEN MANAGER_ID IS NOT NULL THEN '사원' -- OR USE, 'ELSE'
END AS 구분
FROM EMPLOYEE;

SELECT DISTINCT MANAGER_ID FROM EMPLOYEE -- DISTINCT 중복 제거
WHERE MANAGER_ID IS NOT NULL;

SELECT EMP_ID, EMP_NAME, DEPT_CODE,
CASE 
WHEN EMP_ID IN (SELECT DISTINCT MANAGER_ID FROM EMPLOYEE
WHERE MANAGER_ID IS NOT NULL)
THEN '사수'
ELSE'사원'
END AS 구분
FROM EMPLOYEE;

/*
    비교대상 > ANY(SUBQUERY) : 여러개의 결과값 중에서 "한개라도" 클 경우
                              (= 여러 개의 결과값 중에서 가장 작은 값보다 클 경우)
    비교대상 < ANY(SUBQUERY) : 여러개의 결과값 중에서 "한개라도" 작을 경우
                              (= 여러 개의 결과값 중에서 가장 큰 값보다 클 경우)
*/

-- 대리 직급임에도 불구하고 과장 직급들의 최소 급여보다 많이 받는
-- 직원의 사번, 이름, 직급명, 급여 조회

SELECT * FROM EMPLOYEE;
SELECT * FROM JOB;

SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY FROM EMPLOYEE
JOIN JOB USING (JOB_CODE);


SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '대리'; -- 대리 직급

SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '과장'; -- 과장 직급


-- MIN() VERSION
SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY 
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '대리'
AND SALARY > (SELECT MIN(SALARY)
              FROM EMPLOYEE E2
              JOIN JOB J2 ON E2.JOB_CODE = J2.JOB_CODE
              WHERE J2.JOB_NAME = '과장');

-- ANY() VERSION
SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY 
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '대리' -- QUERY PART 1
AND SALARY > ANY -- CONDITION
(SELECT SALARY FROM EMPLOYEE -- QUERY PART 2
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '과장');

/*
    비교대상 > ALL(SUBQUERY) : 여러개의 "모든" 결과값들 보다 클 경우
    비교대상 < ALL(SUBQUERY) : 여러개의 "모든" 결과값들 보다 작을 경우
*/

-- 과장 직급임에도 차장 직급의 최대 급여보다 더 많이 받는 직원들 조회

SELECT * FROM EMPLOYEE
JOIN JOB USING (JOB_CODE);

SELECT EMP_NAME, JOB_NAME, SALARY FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '차장';

SELECT EMP_NAME, JOB_NAME, SALARY FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '과장';

SELECT EMP_NAME, JOB_NAME, SALARY FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '과장'
AND SALARY > ALL
(SELECT SALARY FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '차장');

/*
    3. 다중열 SUBQUERY
     - 서브쿼리의 조회 결과값이 한 행이지만 컬럼이 여러개일 때 (한 행 여러 열)
*/