CREATE TABLE LOTTO (
    drawNo NUMBER,
    drawDate DATE,  -- date → drawDate로 변경
    num1 NUMBER,
    num2 NUMBER,
    num3 NUMBER,
    num4 NUMBER,
    num5 NUMBER,
    num6 NUMBER,
    bonus NUMBER
);

SELECT * FROM LOTTO;


/*

NORMAL DISTRIBUTION (FREQUENCY OF NUMBER)

*/
-- NORMAL DISTRIBUTION OF NUMBER SLOT 1
SELECT num1, COUNT(*) AS FREQUENCY
FROM LOTTO
GROUP BY num1
ORDER BY FREQUENCY DESC
FETCH FIRST 5 ROWS ONLY;

-- SELECT
--   SUM(CASE WHEN MOD(num1, 2) = 0 THEN 1 ELSE 0 END) AS even_count,
--   COUNT(*) AS total_count,
--   ROUND(1.0 * SUM(CASE WHEN MOD(num1, 2) = 0 THEN 1 ELSE 0 END) / COUNT(*), 4) AS even_ratio
-- FROM LOTTO;
-- -- RESULT 46% TO BE EVEN

SELECT
  COUNT(CASE WHEN MOD(num1, 2) = 0 THEN 1 END) AS even_count,
  COUNT(CASE WHEN MOD(num1, 2) = 1 THEN 1 END) AS odd_count,
  ROUND(1.0 * COUNT(CASE WHEN MOD(num1, 2) = 0 THEN 1 END) / NULLIF(COUNT(CASE WHEN MOD(num1, 2) = 1 THEN 1 END), 0), 4) AS even_odds
FROM LOTTO;
-- ODDS FOR EVEN Is 0.87

-- NORMAL DISTRIBUTION OF NUMBER SLOT 2
SELECT num2, COUNT(*) AS FREQUENCY
FROM LOTTO
GROUP BY num2
ORDER BY FREQUENCY DESC
FETCH FIRST 5 ROWS ONLY;

SELECT
  COUNT(CASE WHEN MOD(num2, 2) = 0 THEN 1 END) AS even_count,
  COUNT(CASE WHEN MOD(num2, 2) = 1 THEN 1 END) AS odd_count,
  ROUND(1.0 * COUNT(CASE WHEN MOD(num2, 2) = 0 THEN 1 END) / NULLIF(COUNT(CASE WHEN MOD(num2, 2) = 1 THEN 1 END), 0), 4) AS even_odds
FROM LOTTO;
-- ODDS FOR EVEN IS 1.0


-- NORMAL DISTRIBUTION OF NUMBER SLOT 3
SELECT num3, COUNT(*) AS FREQUENCY
FROM LOTTO
GROUP BY num3
ORDER BY FREQUENCY DESC
FETCH FIRST 5 ROWS ONLY;

SELECT
  COUNT(CASE WHEN MOD(num3, 2) = 0 THEN 1 END) AS even_count,
  COUNT(CASE WHEN MOD(num3, 2) = 1 THEN 1 END) AS odd_count,
  ROUND(1.0 * COUNT(CASE WHEN MOD(num3, 2) = 0 THEN 1 END) / NULLIF(COUNT(CASE WHEN MOD(num3, 2) = 1 THEN 1 END), 0), 4) AS even_odds
FROM LOTTO;
-- ODDS FOR EVEN is 1.0

-- NORMAL DISTRIBUTION OF NUMBER SLOT 4
SELECT num4, COUNT(*) AS FREQUENCY
FROM LOTTO
GROUP BY num4
ORDER BY FREQUENCY DESC
FETCH FIRST 5 ROWS ONLY;

SELECT
  COUNT(CASE WHEN MOD(num4, 2) = 0 THEN 1 END) AS even_count,
  COUNT(CASE WHEN MOD(num4, 2) = 1 THEN 1 END) AS odd_count,
  ROUND(1.0 * COUNT(CASE WHEN MOD(num4, 2) = 0 THEN 1 END) / NULLIF(COUNT(CASE WHEN MOD(num4, 2) = 1 THEN 1 END), 0), 4) AS even_odds
FROM LOTTO;
-- ODDS FOR EVEN is 0.96

-- NORMAL DISTRIBUTION OF NUMBER SLOT 5
SELECT num5, COUNT(*) AS FREQUENCY
FROM LOTTO
GROUP BY num5
ORDER BY FREQUENCY DESC
FETCH FIRST 5 ROWS ONLY;

SELECT
  COUNT(CASE WHEN MOD(num5, 2) = 0 THEN 1 END) AS even_count,
  COUNT(CASE WHEN MOD(num5, 2) = 1 THEN 1 END) AS odd_count,
  ROUND(1.0 * COUNT(CASE WHEN MOD(num5, 2) = 0 THEN 1 END) / NULLIF(COUNT(CASE WHEN MOD(num5, 2) = 1 THEN 1 END), 0), 4) AS even_odds
FROM LOTTO;
-- ODDS FOR EVEN is 0.99

-- NORMAL DISTRIBUTION OF NUMBER SLOT 6
SELECT num6, COUNT(*) AS FREQUENCY
FROM LOTTO
GROUP BY num6
ORDER BY FREQUENCY DESC
FETCH FIRST 5 ROWS ONLY;

SELECT
  COUNT(CASE WHEN MOD(num6, 2) = 0 THEN 1 END) AS even_count,
  COUNT(CASE WHEN MOD(num6, 2) = 1 THEN 1 END) AS odd_count,
  ROUND(1.0 * COUNT(CASE WHEN MOD(num6, 2) = 0 THEN 1 END) / NULLIF(COUNT(CASE WHEN MOD(num6, 2) = 1 THEN 1 END), 0), 4) AS even_odds
FROM LOTTO;
-- ODDS FOR EVEN is 0.88

-- NORMAL DISTRIBUTION OF BONUS SLOT
SELECT BONUS, COUNT(*) AS FREQUENCY
FROM LOTTO
GROUP BY BONUS
ORDER BY FREQUENCY DESC
FETCH FIRST 5 ROWS ONLY;

SELECT
  COUNT(CASE WHEN MOD(BONUS, 2) = 0 THEN 1 END) AS even_count,
  COUNT(CASE WHEN MOD(BONUS, 2) = 1 THEN 1 END) AS odd_count,
  ROUND(1.0 * COUNT(CASE WHEN MOD(BONUS, 2) = 0 THEN 1 END) / NULLIF(COUNT(CASE WHEN MOD(BONUS, 2) = 1 THEN 1 END), 0), 4) AS even_odds
FROM LOTTO;
-- ODDS FOR EVEN is 1.01


/*

CONSECUTIVE DRAW REPEATING NUMBER

*/

SELECT drawNo, num2, prev_num2
FROM (
  SELECT drawNo, num2,
         LAG(drawNo) OVER (ORDER BY drawNo) AS prev_drawNo,
         LAG(num2) OVER (ORDER BY drawNo) AS prev_num2
  FROM lotto
)
WHERE num2 = prev_num2;
/*
    필터 #2
    분석
    연속적으로 같은 번호가 나오는 확률은 극저조함으로
    최신 로또번호에 따라 그 해당번호는 풀에서 누락
*/
